import type { TemplateField } from "../types";

export const hyreskontraktFields: TemplateField[] = [
  // Hyresvärd
  {
    name: "hyresvard_namn",
    label: "Hyresvärdens namn",
    type: "text",
    required: true,
    placeholder: "Förnamn Efternamn / Företagsnamn",
    section: "Hyresvärd",
  },
  {
    name: "hyresvard_personnummer",
    label: "Personnummer / Org.nr",
    type: "text",
    required: true,
    placeholder: "YYYYMMDD-XXXX / XXXXXX-XXXX",
    section: "Hyresvärd",
  },
  {
    name: "hyresvard_adress",
    label: "Adress",
    type: "text",
    required: true,
    placeholder: "Gatuadress, postnummer, ort",
    section: "Hyresvärd",
  },
  {
    name: "hyresvard_telefon",
    label: "Telefon",
    type: "phone",
    required: false,
    placeholder: "07X-XXX XX XX",
    section: "Hyresvärd",
  },

  // Hyresgäst
  {
    name: "hyresgast_namn",
    label: "Hyresgästens namn",
    type: "text",
    required: true,
    placeholder: "Förnamn Efternamn",
    section: "Hyresgäst",
  },
  {
    name: "hyresgast_personnummer",
    label: "Personnummer",
    type: "text",
    required: true,
    placeholder: "YYYYMMDD-XXXX",
    section: "Hyresgäst",
  },
  {
    name: "hyresgast_telefon",
    label: "Telefon",
    type: "phone",
    required: false,
    placeholder: "07X-XXX XX XX",
    section: "Hyresgäst",
  },
  {
    name: "hyresgast_email",
    label: "E-post",
    type: "email",
    required: false,
    placeholder: "namn@exempel.se",
    section: "Hyresgäst",
  },

  // Lägenhet/objekt
  {
    name: "objekt_adress",
    label: "Lägenhetens adress",
    type: "text",
    required: true,
    placeholder: "Gatuadress, lägenhetsnummer",
    section: "Hyresobjekt",
  },
  {
    name: "objekt_typ",
    label: "Typ av bostad",
    type: "select",
    required: true,
    section: "Hyresobjekt",
    options: [
      { value: "lagenhet", label: "Lägenhet" },
      { value: "rum", label: "Rum" },
      { value: "hus", label: "Hus" },
      { value: "stuga", label: "Stuga" },
    ],
  },
  {
    name: "objekt_storlek",
    label: "Storlek (kvm)",
    type: "number",
    required: true,
    placeholder: "65",
    section: "Hyresobjekt",
  },
  {
    name: "antal_rum",
    label: "Antal rum",
    type: "select",
    required: true,
    section: "Hyresobjekt",
    options: [
      { value: "1", label: "1 rum" },
      { value: "1.5", label: "1,5 rum" },
      { value: "2", label: "2 rum" },
      { value: "2.5", label: "2,5 rum" },
      { value: "3", label: "3 rum" },
      { value: "3.5", label: "3,5 rum" },
      { value: "4", label: "4 rum" },
      { value: "5+", label: "5+ rum" },
    ],
  },

  // Hyresvillkor
  {
    name: "hyra",
    label: "Månadshyra (SEK)",
    type: "number",
    required: true,
    placeholder: "8500",
    section: "Hyresvillkor",
  },
  {
    name: "deposition",
    label: "Deposition (SEK)",
    type: "number",
    required: false,
    placeholder: "0",
    section: "Hyresvillkor",
  },
  {
    name: "betalningsdag",
    label: "Betalningsdag i månaden",
    type: "select",
    required: true,
    section: "Hyresvillkor",
    options: [
      { value: "sista", label: "Sista vardagen" },
      { value: "1", label: "Den 1:a" },
      { value: "25", label: "Den 25:e" },
      { value: "28", label: "Den 28:e" },
    ],
  },
  {
    name: "inflyttningsdatum",
    label: "Inflyttningsdatum",
    type: "date",
    required: true,
    section: "Hyresvillkor",
  },
  {
    name: "kontraktstid",
    label: "Kontraktstid",
    type: "select",
    required: true,
    section: "Hyresvillkor",
    options: [
      { value: "tillsvidare", label: "Tillsvidare" },
      { value: "6_manader", label: "6 månader" },
      { value: "1_ar", label: "1 år" },
      { value: "2_ar", label: "2 år" },
    ],
  },
  {
    name: "uppsagningstid",
    label: "Uppsägningstid",
    type: "select",
    required: true,
    section: "Hyresvillkor",
    options: [
      { value: "1_manad", label: "1 månad" },
      { value: "2_manader", label: "2 månader" },
      { value: "3_manader", label: "3 månader" },
    ],
  },

  // Övrigt
  {
    name: "standardvillkor",
    label: "Standardvillkor",
    type: "textarea",
    required: false,
    section: "Övrigt",
    defaultValue:
      "Hyresgästen förbinder sig att väl vårda lägenheten och inte utan hyresvärdens skriftliga medgivande överlåta hyresrätten eller upplåta lägenheten i andra hand. Hyresgästen ansvarar för skador som uppstår genom eget vållande. Vid avflyttning ska lägenheten återställas i det skick den var vid inflyttning, med hänsyn till normalt slitage.",
  },
  {
    name: "ovriga_villkor",
    label: "Övriga villkor",
    type: "textarea",
    required: false,
    placeholder: "T.ex. husdjur tillåtet, parkering ingår...",
    section: "Övrigt",
  },
  {
    name: "ort",
    label: "Ort",
    type: "text",
    required: true,
    placeholder: "Stockholm",
    section: "Övrigt",
  },
  {
    name: "datum",
    label: "Datum",
    type: "date",
    required: true,
    section: "Övrigt",
  },
];
