import type { TemplateField } from "../types";

export const kopekontraktBilFields: TemplateField[] = [
  // Säljare
  {
    name: "saljare_namn",
    label: "Säljarens namn",
    type: "text",
    required: true,
    placeholder: "Förnamn Efternamn",
    section: "Säljare",
  },
  {
    name: "saljare_personnummer",
    label: "Personnummer",
    type: "text",
    required: true,
    placeholder: "YYYYMMDD-XXXX",
    section: "Säljare",
  },
  {
    name: "saljare_adress",
    label: "Adress",
    type: "text",
    required: true,
    placeholder: "Gatuadress, postnummer, ort",
    section: "Säljare",
  },
  {
    name: "saljare_telefon",
    label: "Telefon",
    type: "phone",
    required: false,
    placeholder: "07X-XXX XX XX",
    section: "Säljare",
  },

  // Köpare
  {
    name: "kopare_namn",
    label: "Köparens namn",
    type: "text",
    required: true,
    placeholder: "Förnamn Efternamn",
    section: "Köpare",
  },
  {
    name: "kopare_personnummer",
    label: "Personnummer",
    type: "text",
    required: true,
    placeholder: "YYYYMMDD-XXXX",
    section: "Köpare",
  },
  {
    name: "kopare_adress",
    label: "Adress",
    type: "text",
    required: true,
    placeholder: "Gatuadress, postnummer, ort",
    section: "Köpare",
  },
  {
    name: "kopare_telefon",
    label: "Telefon",
    type: "phone",
    required: false,
    placeholder: "07X-XXX XX XX",
    section: "Köpare",
  },

  // Fordon
  {
    name: "marke",
    label: "Märke",
    type: "text",
    required: true,
    placeholder: "T.ex. Volvo",
    section: "Fordon",
  },
  {
    name: "modell",
    label: "Modell",
    type: "text",
    required: true,
    placeholder: "T.ex. V70",
    section: "Fordon",
  },
  {
    name: "arsmodell",
    label: "Årsmodell",
    type: "number",
    required: true,
    placeholder: "2020",
    section: "Fordon",
  },
  {
    name: "registreringsnummer",
    label: "Registreringsnummer",
    type: "text",
    required: true,
    placeholder: "ABC 123",
    section: "Fordon",
  },
  {
    name: "chassinummer",
    label: "Chassinummer (VIN)",
    type: "text",
    required: false,
    placeholder: "YV1SW...",
    section: "Fordon",
  },
  {
    name: "matarstallning",
    label: "Mätarställning (km)",
    type: "number",
    required: true,
    placeholder: "85000",
    section: "Fordon",
  },
  {
    name: "farg",
    label: "Färg",
    type: "text",
    required: false,
    placeholder: "T.ex. Svart metallic",
    section: "Fordon",
  },
  {
    name: "bransle",
    label: "Bränsle",
    type: "select",
    required: true,
    section: "Fordon",
    options: [
      { value: "bensin", label: "Bensin" },
      { value: "diesel", label: "Diesel" },
      { value: "el", label: "El" },
      { value: "hybrid", label: "Hybrid" },
      { value: "laddhybrid", label: "Laddhybrid" },
    ],
  },

  // Pris och betalning
  {
    name: "kopeskilling",
    label: "Köpeskilling (SEK)",
    type: "number",
    required: true,
    placeholder: "150000",
    section: "Pris och betalning",
  },
  {
    name: "betalningssatt",
    label: "Betalningssätt",
    type: "select",
    required: true,
    section: "Pris och betalning",
    options: [
      { value: "kontant", label: "Kontant" },
      { value: "bankoverföring", label: "Banköverföring" },
      { value: "swish", label: "Swish" },
    ],
  },
  {
    name: "betalningsdag",
    label: "Betalningsdag",
    type: "date",
    required: true,
    section: "Pris och betalning",
  },

  // Skick
  {
    name: "besiktning",
    label: "Besiktning",
    type: "select",
    required: true,
    section: "Skick och garanti",
    options: [
      { value: "godkand", label: "Godkänd besiktning" },
      { value: "ej_besiktigad", label: "Ej besiktigad" },
      { value: "anmarkning", label: "Godkänd med anmärkning" },
    ],
  },
  {
    name: "garantier",
    label: "Garantier/Anmärkningar",
    type: "textarea",
    required: false,
    placeholder: "T.ex. kända fel, garantier som kvarstår...",
    section: "Skick och garanti",
  },

  // Överlåtelse
  {
    name: "overlatelsedag",
    label: "Överlåtelsedag",
    type: "date",
    required: true,
    section: "Överlåtelse",
  },
  {
    name: "standardvillkor",
    label: "Standardvillkor",
    type: "textarea",
    required: false,
    section: "Överlåtelse",
    defaultValue:
      "Försäljningen sker i befintligt skick om inget annat anges. Köparen har besiktigat objektet och godkänner dess skick. Äganderätt och risk övergår till köparen vid överlåtelsetillfället. Säljaren garanterar att objektet inte är behäftat med skulder, panträtter eller andra belastningar.",
  },
  {
    name: "ovriga_villkor",
    label: "Övriga villkor",
    type: "textarea",
    required: false,
    placeholder: "T.ex. vinterdäck ingår, extranycklar...",
    section: "Överlåtelse",
  },
  {
    name: "ort",
    label: "Ort",
    type: "text",
    required: true,
    placeholder: "Stockholm",
    section: "Överlåtelse",
  },
  {
    name: "datum",
    label: "Datum",
    type: "date",
    required: true,
    section: "Överlåtelse",
  },
];
