import type { TemplateField } from "../types";

export const kopekontraktBatFields: TemplateField[] = [
  // Säljare
  {
    name: "saljare_namn",
    label: "Säljarens namn",
    type: "text",
    required: true,
    placeholder: "Förnamn Efternamn",
    section: "Säljare",
  },
  {
    name: "saljare_personnummer",
    label: "Personnummer",
    type: "text",
    required: true,
    placeholder: "YYYYMMDD-XXXX",
    section: "Säljare",
  },
  {
    name: "saljare_adress",
    label: "Adress",
    type: "text",
    required: true,
    placeholder: "Gatuadress, postnummer, ort",
    section: "Säljare",
  },
  {
    name: "saljare_telefon",
    label: "Telefon",
    type: "phone",
    required: false,
    placeholder: "07X-XXX XX XX",
    section: "Säljare",
  },

  // Köpare
  {
    name: "kopare_namn",
    label: "Köparens namn",
    type: "text",
    required: true,
    placeholder: "Förnamn Efternamn",
    section: "Köpare",
  },
  {
    name: "kopare_personnummer",
    label: "Personnummer",
    type: "text",
    required: true,
    placeholder: "YYYYMMDD-XXXX",
    section: "Köpare",
  },
  {
    name: "kopare_adress",
    label: "Adress",
    type: "text",
    required: true,
    placeholder: "Gatuadress, postnummer, ort",
    section: "Köpare",
  },
  {
    name: "kopare_telefon",
    label: "Telefon",
    type: "phone",
    required: false,
    placeholder: "07X-XXX XX XX",
    section: "Köpare",
  },

  // Båt
  {
    name: "battyp",
    label: "Båttyp",
    type: "select",
    required: true,
    section: "Båt",
    options: [
      { value: "segelbat", label: "Segelbåt" },
      { value: "motorbat", label: "Motorbåt" },
      { value: "rib", label: "RIB" },
      { value: "jolly", label: "Jolly/Eka" },
      { value: "kajak_kanot", label: "Kajak/Kanot" },
      { value: "annan", label: "Annan" },
    ],
  },
  {
    name: "marke",
    label: "Märke/Tillverkare",
    type: "text",
    required: true,
    placeholder: "T.ex. Bayliner, Nimbus",
    section: "Båt",
  },
  {
    name: "modell",
    label: "Modell",
    type: "text",
    required: true,
    placeholder: "T.ex. 175 BR",
    section: "Båt",
  },
  {
    name: "arsmodell",
    label: "Årsmodell",
    type: "number",
    required: true,
    placeholder: "2018",
    section: "Båt",
  },
  {
    name: "langd",
    label: "Längd (fot/meter)",
    type: "text",
    required: true,
    placeholder: "T.ex. 17 fot / 5,2 m",
    section: "Båt",
  },
  {
    name: "registreringsnummer",
    label: "Registreringsnummer",
    type: "text",
    required: false,
    placeholder: "Om registrerad hos Transportstyrelsen",
    section: "Båt",
  },
  {
    name: "hin_nummer",
    label: "HIN-nummer (skrovnummer)",
    type: "text",
    required: false,
    placeholder: "Hull Identification Number",
    section: "Båt",
  },

  // Motor
  {
    name: "motor_marke",
    label: "Motor märke/modell",
    type: "text",
    required: false,
    placeholder: "T.ex. Mercury 115 hk",
    section: "Motor",
  },
  {
    name: "motor_effekt",
    label: "Motoreffekt (hk)",
    type: "number",
    required: false,
    placeholder: "115",
    section: "Motor",
  },
  {
    name: "motor_timmar",
    label: "Gångtimmar",
    type: "number",
    required: false,
    placeholder: "350",
    section: "Motor",
  },
  {
    name: "drivmedel",
    label: "Drivmedel",
    type: "select",
    required: false,
    section: "Motor",
    options: [
      { value: "bensin", label: "Bensin" },
      { value: "diesel", label: "Diesel" },
      { value: "el", label: "El" },
      { value: "ingen", label: "Ingen motor (segel/rodd)" },
    ],
  },

  // Pris och betalning
  {
    name: "kopeskilling",
    label: "Köpeskilling (SEK)",
    type: "number",
    required: true,
    placeholder: "85000",
    section: "Pris och betalning",
  },
  {
    name: "betalningssatt",
    label: "Betalningssätt",
    type: "select",
    required: true,
    section: "Pris och betalning",
    options: [
      { value: "kontant", label: "Kontant" },
      { value: "bankoverföring", label: "Banköverföring" },
      { value: "swish", label: "Swish" },
    ],
  },
  {
    name: "betalningsdag",
    label: "Betalningsdag",
    type: "date",
    required: true,
    section: "Pris och betalning",
  },

  // Tillbehör och skick
  {
    name: "tillbehor",
    label: "Tillbehör som ingår",
    type: "textarea",
    required: false,
    placeholder: "T.ex. båttrailer, kapell, livvästar, ankare, GPS...",
    section: "Tillbehör och skick",
  },
  {
    name: "skick",
    label: "Skick/Anmärkningar",
    type: "textarea",
    required: false,
    placeholder: "Beskriv båtens skick och eventuella kända fel...",
    section: "Tillbehör och skick",
  },

  // Överlåtelse
  {
    name: "overlatelsedag",
    label: "Överlåtelsedag",
    type: "date",
    required: true,
    section: "Överlåtelse",
  },
  {
    name: "forvaringsplats",
    label: "Båtens förvaringsplats",
    type: "text",
    required: false,
    placeholder: "T.ex. Djurgårdens båtklubb, plats 42",
    section: "Överlåtelse",
  },
  {
    name: "standardvillkor",
    label: "Standardvillkor",
    type: "textarea",
    required: false,
    section: "Överlåtelse",
    defaultValue:
      "Försäljningen sker i befintligt skick om inget annat anges. Köparen har besiktigat objektet och godkänner dess skick. Äganderätt och risk övergår till köparen vid överlåtelsetillfället. Säljaren garanterar att objektet inte är behäftat med skulder, panträtter eller andra belastningar.",
  },
  {
    name: "ovriga_villkor",
    label: "Övriga villkor",
    type: "textarea",
    required: false,
    placeholder: "Eventuella tilläggsvillkor...",
    section: "Överlåtelse",
  },
  {
    name: "ort",
    label: "Ort",
    type: "text",
    required: true,
    placeholder: "Stockholm",
    section: "Överlåtelse",
  },
  {
    name: "datum",
    label: "Datum",
    type: "date",
    required: true,
    section: "Överlåtelse",
  },
];
